# Generated by Django 4.2.4 on 2023-08-29 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CheckList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=500, null=True, verbose_name='номер п/п')),
                ('cod_kp_overall', models.CharField(blank=True, max_length=500, null=True, verbose_name='Код КП(общий)')),
                ('cod_kp_intervall', models.CharField(blank=True, max_length=500, null=True, verbose_name='Код КП(промежуточный)')),
                ('name_ip', models.CharField(blank=True, max_length=500, null=True, verbose_name='Наименование ИП')),
                ('description_ip', models.CharField(blank=True, max_length=500, null=True, verbose_name='Описание КП')),
                ('pereodiction_carriage', models.CharField(blank=True, max_length=500, null=True, verbose_name='Переодичность проведения')),
                ('counting_abillity', models.CharField(blank=True, max_length=500, null=True, verbose_name='Способ подсчета результаты проведения КП')),
                ('responsible_group', models.CharField(blank=True, max_length=500, null=True, verbose_name='Подразделение, ответственное за проведение контрольной процедуры')),
                ('perforemr_kp', models.CharField(blank=True, max_length=500, null=True, verbose_name='Исполнитель КП')),
                ('number_complete', models.CharField(blank=True, max_length=500, null=True, verbose_name='Количество выполненых КП')),
                ('number_mistakes', models.CharField(blank=True, max_length=500, null=True, verbose_name='Количество выявленных ошибок')),
            ],
        ),
        migrations.CreateModel(
            name='Columns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column1', models.CharField(blank=True, max_length=500, null=True, verbose_name='Столб-1')),
                ('column2', models.CharField(blank=True, max_length=500, null=True, verbose_name='Столб-2')),
                ('column3', models.CharField(blank=True, max_length=500, null=True, verbose_name='Столб-3')),
                ('column4', models.CharField(blank=True, max_length=500, null=True, verbose_name='Столб-4')),
                ('column5', models.CharField(blank=True, max_length=500, null=True, verbose_name='Столб-5')),
                ('column6', models.CharField(blank=True, max_length=500, null=True, verbose_name='Столб-6')),
                ('column7', models.CharField(blank=True, max_length=500, null=True, verbose_name='Столб-7')),
                ('column8', models.CharField(blank=True, max_length=500, null=True, verbose_name='Столб-8')),
                ('column9', models.CharField(blank=True, max_length=500, null=True, verbose_name='Столб-9')),
                ('column10', models.CharField(blank=True, max_length=500, null=True, verbose_name='Столб-10')),
                ('column11', models.CharField(blank=True, max_length=500, null=True, verbose_name='Столб-11')),
                ('column12', models.CharField(blank=True, max_length=500, null=True, verbose_name='Столб-12')),
                ('column13', models.CharField(blank=True, max_length=500, null=True, verbose_name='Столб-13')),
                ('column14', models.CharField(blank=True, max_length=500, null=True, verbose_name='Столб-14')),
                ('column15', models.CharField(blank=True, max_length=500, null=True, verbose_name='Столб-15')),
            ],
        ),
        migrations.CreateModel(
            name='Reestr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.CharField(blank=True, max_length=500, null=True, verbose_name='номер п/п')),
                ('cod_kp_inter', models.CharField(blank=True, max_length=500, null=True, verbose_name='Код КП(промежуточный)')),
                ('performer_ip', models.CharField(blank=True, max_length=500, null=True, verbose_name='Исполнитель ИП')),
                ('chek_num', models.CharField(blank=True, max_length=500, null=True, verbose_name='номер чек листа')),
                ('obj_control', models.CharField(blank=True, max_length=500, null=True, verbose_name='Обьект контроля')),
                ('date_document', models.CharField(blank=True, max_length=500, null=True, verbose_name='Дата документа')),
                ('num_document', models.CharField(blank=True, max_length=500, null=True, verbose_name='Номер документа')),
                ('colvo_doc', models.CharField(blank=True, max_length=500, null=True, verbose_name='Количество документов/операций')),
                ('colvo_errors', models.CharField(blank=True, max_length=500, null=True, verbose_name='Количество ошибок/нарушений')),
                ('notes', models.CharField(blank=True, max_length=500, null=True, verbose_name='Примечаний')),
                ('cheklist1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.checklist')),
            ],
        ),
        migrations.AddField(
            model_name='checklist',
            name='cheklist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.columns'),
        ),
    ]
