# Generated by Django 4.2.4 on 2023-08-20 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='columns',
            name='column10',
        ),
        migrations.AddField(
            model_name='checklist',
            name='cheklist',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='services.columns'),
            preserve_default=False,
        ),
    ]
