# Generated by Django 4.2.4 on 2023-08-21 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_remove_columns_column10_checklist_cheklist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reestr',
            old_name='cheklist',
            new_name='cheklist1',
        ),
    ]
